### ISSUE TITLE
Cant get install to work

### ISSUE THREAD

**Issue by tylergraydev** [sanzgiri/dash-sms#2]
I am trying to get this installed. I cannot get it to go. I am not too expierenced with cmd line. 

D:\Documents\Downloads\dash-sms-master (1)\dash-sms-master>npm install
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm WARN prefer global marked@0.3.6 should be installed with -g

> socketwatcher@0.3.0 install D:\Documents\Downloads\dash-sms-master (1)\dash-sms-master\node_modules\socketwatcher
> node-gyp rebuild

D:\Documents\Downloads\dash-sms-master (1)\dash-sms-master\node_modules\socketwatcher>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  socket_watcher.cpp
  win_delay_load_hook.cc
..\socket_watcher.cpp(104): warning C4996: 'v8::Function::NewInstance': was declared deprecated [D:\Documents\Downloads
\dash-sms-master (1)\dash-sms-master\node_modules\socketwatcher\build\socketwatcher.vcxproj]
  c:\users\tyler\.node-gyp\7.3.0\include\node\v8.h(3292): note: see declaration of 'v8::Function::NewInstance'
     Creating library D:\Documents\Downloads\dash-sms-master (1)\dash-sms-master\node_modules\socketwatcher\build\Relea
  se\socketwatcher.lib and object D:\Documents\Downloads\dash-sms-master (1)\dash-sms-master\node_modules\socketwatcher
  \build\Release\socketwatcher.exp
  Generating code
  Finished generating code
  socketwatcher.vcxproj -> D:\Documents\Downloads\dash-sms-master (1)\dash-sms-master\node_modules\socketwatcher\build\
  Release\\socketwatcher.node
  socketwatcher.vcxproj -> D:\Documents\Downloads\dash-sms-master (1)\dash-sms-master\node_modules\socketwatcher\build\
  Release\socketwatcher.pdb (Full PDB)

> pcap@2.0.0 install D:\Documents\Downloads\dash-sms-master (1)\dash-sms-master\node_modules\pcap
> node-gyp rebuild

D:\Documents\Downloads\dash-sms-master (1)\dash-sms-master\node_modules\pcap>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  pcap_binding.cc
  pcap_session.cc
  win_delay_load_hook.cc
..\pcap_session.cc(2): fatal error C1083: Cannot open include file: 'pcap/pcap.h': No such file or directory [D:\Docume
nts\Downloads\dash-sms-master (1)\dash-sms-master\node_modules\pcap\build\pcap_binding.vcxproj]
..\pcap_binding.cc(2): fatal error C1083: Cannot open include file: 'pcap/pcap.h': No such file or directory [D:\Docume
nts\Downloads\dash-sms-master (1)\dash-sms-master\node_modules\pcap\build\pcap_binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Documents\Downloads\dash-sms-master (1)\dash-sms-master\node_modules\pcap
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
dash-sms@1.0.0 D:\Documents\Downloads\dash-sms-master (1)\dash-sms-master
+-- lodash@4.17.4
+-- node-dev@3.1.3
| +-- dateformat@1.0.12
| | +-- get-stdin@4.0.1
| | `-- meow@3.7.0
| |   +-- camelcase-keys@2.1.0
| |   | `-- camelcase@2.1.1
| |   +-- decamelize@1.2.0
| |   +-- loud-rejection@1.6.0
| |   | +-- currently-unhandled@0.4.1
| |   | | `-- array-find-index@1.0.2
| |   | `-- signal-exit@3.0.2
| |   +-- map-obj@1.0.1
| |   +-- normalize-package-data@2.3.5
| |   | +-- hosted-git-info@2.1.5
| |   | +-- is-builtin-module@1.0.0
| |   | | `-- builtin-modules@1.1.1
| |   | `-- validate-npm-package-license@3.0.1
| |   |   +-- spdx-correct@1.0.2
| |   |   | `-- spdx-license-ids@1.2.2
| |   |   `-- spdx-expression-parse@1.0.4
| |   +-- object-assign@4.1.0
| |   +-- read-pkg-up@1.0.1
| |   | +-- find-up@1.1.2
| |   | | `-- path-exists@2.1.0
| |   | `-- read-pkg@1.1.0
| |   |   +-- load-json-file@1.1.0
| |   |   | +-- graceful-fs@4.1.11
| |   |   | +-- parse-json@2.2.0
| |   |   | | `-- error-ex@1.3.0
| |   |   | |   `-- is-arrayish@0.2.1
| |   |   | +-- pify@2.3.0
| |   |   | `-- strip-bom@2.0.0
| |   |   |   `-- is-utf8@0.2.1
| |   |   `-- path-type@1.1.0
| |   +-- redent@1.0.0
| |   | +-- indent-string@2.1.0
| |   | | `-- repeating@2.0.1
| |   | |   `-- is-finite@1.0.2
| |   | |     `-- number-is-nan@1.0.1
| |   | `-- strip-indent@1.0.1
| |   `-- trim-newlines@1.0.0
| +-- dynamic-dedupe@0.2.0
| | `-- xtend@2.0.6
| |   +-- is-object@0.1.2
| |   `-- object-keys@0.2.0
| |     +-- foreach@2.0.5
| |     +-- indexof@0.0.1
| |     `-- is@0.2.7
| +-- filewatcher@3.0.1
| | `-- debounce@1.0.0
| |   `-- date-now@1.0.1
| +-- minimist@1.2.0
| +-- node-notifier@4.6.1
| | +-- cli-usage@0.1.4
| | | +-- marked@0.3.6
| | | `-- marked-terminal@1.7.0
| | |   +-- cardinal@1.0.0
| | |   | +-- ansicolors@0.2.1
| | |   | `-- redeyed@1.0.1
| | |   |   `-- esprima@3.0.0
| | |   +-- cli-table@0.3.1
| | |   | `-- colors@1.0.3
| | |   +-- lodash.assign@4.2.0
| | |   `-- node-emoji@1.4.3
| | |     `-- string.prototype.codepointat@0.2.0
| | +-- growly@1.3.0
| | +-- lodash.clonedeep@3.0.2
| | | +-- lodash._baseclone@3.3.0
| | | | +-- lodash._arraycopy@3.0.0
| | | | +-- lodash._arrayeach@3.0.0
| | | | +-- lodash._baseassign@3.2.0
| | | | | `-- lodash._basecopy@3.0.1
| | | | +-- lodash._basefor@3.0.3
| | | | +-- lodash.isarray@3.0.4
| | | | `-- lodash.keys@3.1.2
| | | |   +-- lodash._getnative@3.9.1
| | | |   `-- lodash.isarguments@3.1.0
| | | `-- lodash._bindcallback@3.0.1
| | +-- semver@5.3.0
| | +-- shellwords@0.1.0
| | `-- which@1.2.12
| |   `-- isexe@1.1.2
| `-- resolve@1.2.0
+-- twilio@2.11.1
| +-- deprecate@0.1.0
| +-- jsonwebtoken@5.4.1
| | +-- jws@3.1.4
| | | +-- base64url@2.0.0
| | | +-- jwa@1.1.5
| | | | +-- buffer-equal-constant-time@1.0.1
| | | | `-- ecdsa-sig-formatter@1.0.9
| | | `-- safe-buffer@5.0.1
| | `-- ms@0.7.2
| +-- q@0.9.7
| +-- request@2.74.0
| | +-- aws-sign2@0.6.0
| | +-- aws4@1.5.0
| | +-- bl@1.1.2
| | | `-- readable-stream@2.0.6
| | |   +-- core-util-is@1.0.2
| | |   +-- inherits@2.0.3
| | |   +-- isarray@1.0.0
| | |   +-- process-nextick-args@1.0.7
| | |   +-- string_decoder@0.10.31
| | |   `-- util-deprecate@1.0.2
| | +-- caseless@0.11.0
| | +-- combined-stream@1.0.5
| | | `-- delayed-stream@1.0.0
| | +-- extend@3.0.0
| | +-- forever-agent@0.6.1
| | +-- form-data@1.0.1
| | | `-- async@2.1.4
| | +-- har-validator@2.0.6
| | | +-- chalk@1.1.3
| | | | +-- ansi-styles@2.2.1
| | | | +-- escape-string-regexp@1.0.5
| | | | +-- has-ansi@2.0.0
| | | | | `-- ansi-regex@2.0.0
| | | | +-- strip-ansi@3.0.1
| | | | `-- supports-color@2.0.0
| | | +-- commander@2.9.0
| | | | `-- graceful-readlink@1.0.1
| | | +-- is-my-json-valid@2.15.0
| | | | +-- generate-function@2.0.0
| | | | +-- generate-object-property@1.2.0
| | | | | `-- is-property@1.0.2
| | | | +-- jsonpointer@4.0.1
| | | | `-- xtend@4.0.1
| | | `-- pinkie-promise@2.0.1
| | |   `-- pinkie@2.0.4
| | +-- hawk@3.1.3
| | | +-- boom@2.10.1
| | | +-- cryptiles@2.0.5
| | | +-- hoek@2.16.3
| | | `-- sntp@1.0.9
| | +-- http-signature@1.1.1
| | | +-- assert-plus@0.2.0
| | | +-- jsprim@1.3.1
| | | | +-- extsprintf@1.0.2
| | | | +-- json-schema@0.2.3
| | | | `-- verror@1.3.6
| | | `-- sshpk@1.10.1
| | |   +-- asn1@0.2.3
| | |   +-- assert-plus@1.0.0
| | |   +-- bcrypt-pbkdf@1.0.0
| | |   +-- dashdash@1.14.1
| | |   | `-- assert-plus@1.0.0
| | |   +-- ecc-jsbn@0.1.1
| | |   +-- getpass@0.1.6
| | |   | `-- assert-plus@1.0.0
| | |   +-- jodid25519@1.0.2
| | |   +-- jsbn@0.1.0
| | |   `-- tweetnacl@0.14.5
| | +-- is-typedarray@1.0.0
| | +-- isstream@0.1.2
| | +-- json-stringify-safe@5.0.1
| | +-- mime-types@2.1.13
| | | `-- mime-db@1.25.0
| | +-- node-uuid@1.4.7
| | +-- oauth-sign@0.8.2
| | +-- qs@6.2.1
| | +-- stringstream@0.0.5
| | +-- tough-cookie@2.3.2
| | | `-- punycode@1.4.1
| | `-- tunnel-agent@0.4.3
| +-- scmp@0.0.3
| +-- string.prototype.startswith@0.2.0
| `-- underscore@1.8.3
`-- when@3.7.7

npm WARN dash-sms@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pcap@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcap@2.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pcap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pcap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pcap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Documents\Downloads\dash-sms-master (1)\dash-sms-master\npm-debug.log

**Comment by martin8777** [comment]
The problem is you're trying to run it on Windows and not Linux. It worked fine for me on a raspberry pi running raspbian. Pretty sure it's intended just to be run within Linux.

**Comment by sanzgiri** [comment]
Hi tylergraydev - sorry I have not tried this on Windows. It should work fine on a Mac or Linux.
